title: Why is this interesting?
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
  books:
    permalink: '/books/:title/'
    output: true
layout_style: overflow
palette: blue
header:
  title: Why is this interesting?
  tagline: A community of the curious
  profile_img: images/why-is-this-interesting.png
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: '&copy; Yup yup'
  links:
    - text: Subscribe to Why is this interesting?
      url: 'https://whyisthisinteresting.substack.com'
      new_window: false
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
